# Generated by Django 4.2.3 on 2024-11-11 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
